# Generated by Django 5.0.2 on 2024-03-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servers',
            new_name='Server',
        ),
    ]
